# path to file with sample name and condition
samples: config/samples.tsv
units: config/units.tsv

# Merge reads from two sequencing runs
mergeReads:
  activate: True

reference:
  path: resources/reference/Trinity_20210112.fasta
  filename: Trinity_20210112.fasta
  filestem: Trinity_20210112

geneIDType: type_2 #the type of gene identifier; type_1 = "compXX_cXX_seqXX", type_2="TRINITY_DNXXXXX_cX_gX_iX", type_3="SegXX.XX.XXXX"; rule keep_longest_ORF_per_gene and rule make_GTF

# Install according to https://github.com/Trinotate/Trinotate.github.io/wiki/Software-installation-and-data-required
rnammer: ~/local/bin/rnammer-1.2/rnammer #path to rnammer
tmhmm: ~/local/bin/tmhmm-2.0c/bin/tmhmm #path to tmhmm
signalp: ~/local/bin/signalp-4.1/signalp #path to signalp
