# path to file with sample name and condition
samples: config/samples.tsv
units: config/units.tsv

mergeReads:
  activate: False

reference: Trinity_20210112.fasta #place file in folder resources

geneIDType: type_2