# path to file with sample name and condition
samples: config/samples.tsv
units: config/units.tsv

mergeReads:
  activate: True

reference: resources/reference/ARSv1_genome_assembly.fa
reference_gtf: resources/reference/ARSv1_genome_assembly.gtf
proteins: resources/reference/ARSv1_proteins.fa