from snakemake.utils import min_version

min_version("6.4.1")

configfile: "config/config.yaml"

# load rules
include: "rules/general.smk"
include: "rules/reads.smk"
include: "rules/reference.smk"
include: "rules/align.smk"
include: "rules/count.smk"
include: "rules/stats.smk"
include: "rules/pia.smk"

# target rule
rule all:
    input:
        expand("resources/rawdata/{accs}_{read}.fastq", accs=units.loc[:,"sra"], read=["1","2"]),
        expand("results/star/mapping/{accession}/Aligned.out.sam.stats", accession=units.loc[:,"sra"]),
        "results/counts/counts_matrix.txt",
        "results/busco",
        expand("results/opsins/{transcriptome}.fixed_longestORFperGene.opsins.fasta", transcriptome=config["reference"]["filename"])
